<?php

/*
|--------------------------------------------------------------------------
| Trident Routes
|--------------------------------------------------------------------------
|
| This file is auto generated by trident. Any manual change will 
| be overwritten.
|
*/

Route::middleware(['auth'])->group(function () {
});