<?php

/*
|--------------------------------------------------------------------------
| Trident Routes
|--------------------------------------------------------------------------
|
| This file is auto generated by trident. Any manual change will 
| be overwritten.
|
*/

Route::middleware(['auth'])->group(function () {
    Route::resource('/trident/resource/chapter', 'ChapterController');
    Route::resource('/trident/resource/character', 'CharacterController');
    Route::resource('/trident/resource/episode', 'EpisodeController');
    Route::resource('/trident/resource/focus', 'FocusController');
    Route::resource('/trident/resource/focusgoal', 'FocusgoalController');
    Route::resource('/trident/resource/npc', 'NpcController');
    Route::resource('/trident/resource/player', 'PlayerController');
    Route::resource('/trident/resource/session', 'SessionController');
});